### ISSUE TITLE
User Story: Launch Screen

### ISSUE THREAD

**Issue by alexgraffeocohen** [Cosecha/redadalertas#51]
## Overview

![Landing Screen](https://user-images.githubusercontent.com/5783513/47386520-d9cb6400-d6da-11e8-9cde-142e40a88844.png)

As a user, when I launch the app for the first time, I see a landing screen identifying the app and allowing me to being.

## Implementation Steps

- [ ] Create ejected React Native app
- [ ] Create static landing asset for iOS
- [ ] Create static landing asset for Android
- [ ] Create landing screen

## Tech Details

* This seems like a good article for the splash screen: https://medium.com/handlebar-labs/how-to-add-a-splash-screen-to-a-react-native-app-ios-and-android-30a3cec835ae
* Necessary assets are in Dropbox (i.e. the logo and mockups)
* We should be able to do the transparent blue with CSS and React Native components
* We need a high resolution image of a map to place on the bottom
* Use out of the box styles for React Native buttons, but use white text
